builds:
  - id: hapettpsay
    dir: .
    main: ./main.go
    binary: hapettpsay
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 7

archives:
- builds:
  - hapettpsay
  name_template: 'hapettpsay_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE

brews:
- name: hapettpsay
  tap:
    owner: Rid
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: https://github.com/Rid/hapettpsay
  description: "Fast, funny, everyone wanted? new hapettpsay!!"
  folder: Formula
  install: |
    bin.install "hapettpsay"

checksum:
  name_template: 'hapettpsay_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
